### PR TITLE
Upgrade plexus-utils to 4.0.0 plus add plexus-xml 3.0.0

### PR DESCRIPTION
**Pull request by slachiewicz**
We require only xml part of plexus utils

### CODE REVIEW

**Comment by slachiewicz** [comment]
@cstamas @gnodet please check if dependency tree is correct for maven-xml-impl

**Comment by gnodet** [comment]
> @cstamas @gnodet please check if dependency tree is correct for maven-xml-impl

I have the following:
```
+- org.codehaus.plexus:plexus-xml:jar:4.0.0:compile
[INFO] |  \- org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:compile
[INFO] |     +- org.apache.maven:maven-api-xml:jar:4.0.0-alpha-5:compile
[INFO] |     |  \- org.apache.maven:maven-api-meta:jar:4.0.0-alpha-5:compile
[INFO] |     \- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:compile
[INFO] |        \- org.codehaus.plexus:plexus-utils:jar:3.0.24:compile
```
The dependency on `sisu.plexus` is caused by the `XmlPlexusConfiguration` provided by `maven-xml-impl` which extends `org.codehaus.plexus.configuration.DefaultPlexusConfiguration` provided by `sisu.plexus`.   I agree that's not ideal.  Maybe we could flag the dependency from `maven-xml-impl` to `sisu.plexus` as optional ?

**Comment by mcculls** [comment]
That suggests a dependency cycle that could be avoided if the low-level XML classes were available in one dependency and higher-level adapters like `XmlPlexusConfiguration` were in other...

**Comment by mcculls** [comment]
Once everyone's ok with the dependency structure I'm ok merging this - just want to avoid cycles that might cause issues when loading these projects into IDEs.

**Comment by slachiewicz** [comment]
I've downgraded plexus-xml to 3 to keep compatibility with Maven 3

**Review by mcculls — APPROVED** [review]

**Pull request merged**
